from datetime import datetime
from database.db import db

class Uniprot(db.Model):
    __tablename__ = 'membrane_protein_uniprot'
    id = db.Column(db.Integer, primary_key=True)
    uniprot_id = db.Column(db.Text)
    pdb_code = db.Column(db.Text)
    info_type = db.Column(db.Text)
    info_created = db.Column(db.Text)
    info_modified = db.Column(db.Text)
    info_sequence_update = db.Column(db.Text)
    annotation_score = db.Column(db.Float)
    organism_scientific_name = db.Column(db.Text)
    organism_common_name = db.Column(db.Text)
    organism_lineage = db.Column(db.Text)
    secondary_accession = db.Column(db.Text)
    protein_recommended_name = db.Column(db.Text)
    protein_alternative_name = db.Column(db.Text)
    associated_genes = db.Column(db.Text)
    comment_function = db.Column(db.Text)
    comment_interactions = db.Column(db.Text)
    comment_catalytic_activity = db.Column(db.Text)
    comment_subunit = db.Column(db.Text)
    comment_ptm = db.Column(db.Text)
    comment_caution = db.Column(db.Text)
    comment_subcellular_locations = db.Column(db.Text)
    comment_alternative_products = db.Column(db.Text)
    comment_disease_name = db.Column(db.Text)
    comment_disease = db.Column(db.Text)
    comment_similarity = db.Column(db.Text)
    features = db.Column(db.Text)
    references = db.Column(db.Text)
    keywords = db.Column(db.Text)
    sequence_length = db.Column(db.Integer)
    sequence_mass = db.Column(db.Integer)
    extra_attributes = db.Column(db.Text)
    sequence_sequence = db.Column(db.Text)
    molecular_function = db.Column(db.Text)
    cellular_component = db.Column(db.Text)
    biological_process = db.Column(db.Text)
    cross_references = db.Column(db.Text)
