services:
  flask-app:
    image: ebenco36/mpvis_app:latest
    container_name: testmpvis_app
    ports:
      - "${FLASK_RUN_PORT}:8081"
    depends_on:
      - postgres
      - redis
    volumes:
      - flask-app-data:/var/app/data
    networks:
      - app-networks

  postgres:
    container_name: "testmetaMPDB"
    image: postgres:latest
    deploy:
      resources:
        limits:
          memory: 3G 
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-networks

  frontend:
    image: ebenco36/mpfrontend:latest
    container_name: testMPfrontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:${FLASK_RUN_PORT}
    networks:
      - app-networks

  redis:
    image: redis
    deploy:
      resources:
        limits:
          memory: 2G 
    container_name: testmetaMPRedis
    ports:
      - "6379:6379"  # Expose the Redis port
    volumes:
      - redis-data:/data
    networks:
      - app-networks


networks:
  app-networks:
    driver: bridge

volumes:
  flask-app-data:
  pgdata:
  redis-data:
