import os
def str_to_bool(value):
    if value.lower() in ['true', '1', 't', 'y', 'yes']:
        return True
    elif value.lower() in ['false', '0', 'f', 'n', 'no']:
        return False
    else:
        raise ValueError(f"Invalid boolean value: {value}")
    
class Config(object):
    DEBUG = False
    TESTING = False
    SQLALCHEMY_DATABASE_URI = os.getenv('DATABASE_URL')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_SILENCE_UBER_WARNING=1
    SQLALCHEMY_COMMIT_ON_TEARDOWN=False
    
    SECRET_KEY=os.getenv('SECRET_KEY')
    JWT_SECRET_KEY=os.getenv('JWT_SECRET_KEY')
    SECURITY_PASSWORD_SALT=os.getenv('SECURITY_PASSWORD_SALT')
    FLASK_APP=os.getenv('FLASK_APP')
    FLASK_RUN_HOST=os.getenv('FLASK_RUN_HOST')
    FLASK_RUN_PORT=os.getenv('FLASK_RUN_PORT')
    #APP CONFIG
    DB_USER=os.getenv('DB_USER')
    DB_PASSWORD=os.getenv('DB_PASSWORD')
    DB_HOST=os.getenv('DB_HOST')
    DB_PORT=os.getenv('DB_PORT')
    DB_NAME=os.getenv('DB_NAME')

    ADMIN_NAME=os.getenv('ADMIN_NAME')
    ADMIN_EMAIL=os.getenv('ADMIN_EMAIL')
    ADMIN_USERNAME=os.getenv('ADMIN_USERNAME')
    ADMIN_PASSWORD=os.getenv('ADMIN_PASSWORD')
    ADMIN_PHONE=os.getenv('ADMIN_PHONE')
    IS_ADMIN=1

    MAIL_DEFAULT_SENDER=os.getenv('MAIL_DEFAULT_SENDER')
    MAIL_SERVER=os.getenv('MAIL_SERVER')
    MAIL_PORT=os.getenv('MAIL_PORT')
    # I will come back to this later
    # MAIL_USE_TLS=os.getenv('MAIL_USE_TLS')
    # MAIL_USE_SSL=os.getenv('MAIL_USE_SSL')
    MAIL_USERNAME=os.getenv('MAIL_USERNAME')
    MAIL_PASSWORD=os.getenv('MAIL_PASSWORD')
    MAIL_DEBUG=os.getenv('MAIL_DEBUG')

    # Set SSL/TLS version explicitly
    MAIL_SSL_VERSION=os.getenv('MAIL_SSL_VERSION')
    
    # LANG
    BABEL_DEFAULT_LOCALE=os.getenv('BABEL_DEFAULT_LOCALE', 'en')
    BABEL_SUPPORTED_LOCALES=os.getenv('BABEL_SUPPORTED_LOCALES', 'en')
    REDIS_HOST=os.getenv('REDIS_HOST')
    CELERY_BROKER_URL=os.getenv('CELERY_BROKER_URL')
    CELERY_RESULT_BACKEND=os.getenv('CELERY_RESULT_BACKEND')
    CELERY_TIMEZONE=os.getenv('CELERY_TIMEZONE', 'UTC')
    INGESTION_DATASET_BASE_DIR=os.getenv('INGESTION_DATASET_BASE_DIR')
    SEMI_SUPERVISED_MODEL_DIR=os.getenv('SEMI_SUPERVISED_MODEL_DIR')
    DASHBOARD_ANNOTATION_DATASET_PATH=os.getenv('DASHBOARD_ANNOTATION_DATASET_PATH')
    ANNOTATION_DATASET_PATH=os.getenv('ANNOTATION_DATASET_PATH')
    LIVE_GROUP_PREDICTIONS_PATH=os.getenv('LIVE_GROUP_PREDICTIONS_PATH')
    TM_PREDICTION_OUTPUT_CSV=os.getenv('TM_PREDICTION_OUTPUT_CSV')
    OPTIONAL_TM_PREDICTION_BASE_DIR=os.getenv('OPTIONAL_TM_PREDICTION_BASE_DIR')
    TMBED_MODEL_DIR=os.getenv('TMBED_MODEL_DIR')
    TMBED_ENABLED=os.getenv('TMBED_ENABLED', 'true')
    TMBED_REQUIRE_HEALTHCHECK=os.getenv('TMBED_REQUIRE_HEALTHCHECK', 'true')
    TMBED_ALLOW_ARM64=os.getenv('TMBED_ALLOW_ARM64', 'false')
    TM_PREDICTION_BATCH_SIZE=os.getenv('TM_PREDICTION_BATCH_SIZE')
    TM_PREDICTION_MAX_WORKERS=os.getenv('TM_PREDICTION_MAX_WORKERS')
    TM_PREDICTION_USE_GPU=os.getenv('TM_PREDICTION_USE_GPU')
    TM_PREDICTION_INCLUDE_DEEPTMHMM=os.getenv('TM_PREDICTION_INCLUDE_DEEPTMHMM')
    TM_PREDICTION_REQUEST_MODE=os.getenv('TM_PREDICTION_REQUEST_MODE', 'async')
    TM_PREDICTION_RATE_LIMIT_ENABLED=os.getenv('TM_PREDICTION_RATE_LIMIT_ENABLED', 'true')
    TM_PREDICTION_RATE_LIMIT_WINDOW_SECONDS=os.getenv('TM_PREDICTION_RATE_LIMIT_WINDOW_SECONDS', '60')
    TM_PREDICTION_RATE_LIMIT_SEQUENCE_REQUESTS=os.getenv('TM_PREDICTION_RATE_LIMIT_SEQUENCE_REQUESTS', '10')
    TM_PREDICTION_RATE_LIMIT_BACKFILL_REQUESTS=os.getenv('TM_PREDICTION_RATE_LIMIT_BACKFILL_REQUESTS', '2')
    TMALPHAFOLD_STARTUP_CATCHUP_ENABLED=os.getenv('TMALPHAFOLD_STARTUP_CATCHUP_ENABLED')
    TMALPHAFOLD_STARTUP_CATCHUP_STALE_DAYS=os.getenv('TMALPHAFOLD_STARTUP_CATCHUP_STALE_DAYS')
    TMALPHAFOLD_STARTUP_CATCHUP_LOCK_TTL_SECONDS=os.getenv('TMALPHAFOLD_STARTUP_CATCHUP_LOCK_TTL_SECONDS')
    TMALPHAFOLD_STARTUP_CATCHUP_MAX_WORKERS=os.getenv('TMALPHAFOLD_STARTUP_CATCHUP_MAX_WORKERS')
    BIOLIB_TOKEN=os.getenv('BIOLIB_TOKEN')
    CELERY_BEAT_SCHEDULE_FILENAME=os.getenv(
        'CELERY_BEAT_SCHEDULE_FILENAME',
        './celery-beat/celerybeat-schedule'
    )
    SOCKETIO_CORS_ALLOWED_ORIGINS=os.getenv('SOCKETIO_CORS_ALLOWED_ORIGINS', '*')
    SOCKETIO_PING_INTERVAL=os.getenv('SOCKETIO_PING_INTERVAL', '25')
    SOCKETIO_PING_TIMEOUT=os.getenv('SOCKETIO_PING_TIMEOUT', '60')



class ProductionConfig(Config):
    DEBUG = False
    MAIL_SERVER = os.getenv('MAIL_SERVER')
    MAIL_PORT = os.getenv('MAIL_PORT')
    MAIL_USE_TLS = str_to_bool(os.getenv('MAIL_USE_TLS'))
    MAIL_USE_SSL = str_to_bool(os.getenv('MAIL_USE_SSL'))
    MAIL_USERNAME=os.getenv('MAIL_USERNAME')
    MAIL_PASSWORD=os.getenv('MAIL_PASSWORD')
    MAIL_DEFAULT_SENDER=os.getenv('MAIL_DEFAULT_SENDER')
    MAIL_MAX_EMAILS=os.getenv('MAIL_MAX_EMAILS')
    MAIL_ASCII_ATTACHMENTS=os.getenv('MAIL_ASCII_ATTACHMENTS')
    MAIL_DEBUG=os.getenv('MAIL_DEBUG')


class StagingConfig(Config):
    DEVELOPMENT = True
    DEBUG = True
    MAIL_SERVER = os.getenv('MAIL_SERVER')
    MAIL_PORT = os.getenv('MAIL_PORT')
    MAIL_USE_TLS = str_to_bool(os.getenv('MAIL_USE_TLS'))
    MAIL_USE_SSL = str_to_bool(os.getenv('MAIL_USE_SSL'))
    MAIL_USERNAME=os.getenv('MAIL_USERNAME')
    MAIL_PASSWORD=os.getenv('MAIL_PASSWORD')
    MAIL_DEFAULT_SENDER=os.getenv('MAIL_DEFAULT_SENDER')
    MAIL_MAX_EMAILS=os.getenv('MAIL_MAX_EMAILS')
    MAIL_ASCII_ATTACHMENTS=os.getenv('MAIL_ASCII_ATTACHMENTS')
    MAIL_DEBUG=os.getenv('MAIL_DEBUG')


class DevelopmentConfig(Config):
    DEVELOPMENT = True
    DEBUG = True
    MAIL_SERVER = os.getenv('MAIL_SERVER')
    MAIL_PORT = os.getenv('MAIL_PORT')
    MAIL_USE_TLS = str_to_bool(os.getenv('MAIL_USE_TLS'))
    MAIL_USE_SSL = str_to_bool(os.getenv('MAIL_USE_SSL'))
    MAIL_USERNAME=os.getenv('MAIL_USERNAME')
    MAIL_PASSWORD=os.getenv('MAIL_PASSWORD')
    MAIL_DEFAULT_SENDER=os.getenv('MAIL_DEFAULT_SENDER')
    MAIL_MAX_EMAILS=os.getenv('MAIL_MAX_EMAILS')
    MAIL_ASCII_ATTACHMENTS=os.getenv('MAIL_ASCII_ATTACHMENTS')
    MAIL_DEBUG=os.getenv('MAIL_DEBUG')

# Set SSL/TLS version explicitly
# MAIL_SSL_VERSION='TLSv1_2'  # Adjust this based on server requirements




class TestingConfig(Config):
    TESTING = True
